### ISSUE TITLE
Issue with IPv6 prefix

### ISSUE THREAD

**Issue by f466162** [f466162/fritzbox-netcup-dyndns#4]
```
container     | Traceback (most recent call last):
container     |   File "/usr/src/app/./fb-nc-dyndns.py", line 85, in <module>
container     |     last_addresses = main(last_addresses)
container     |   File "/usr/src/app/./fb-nc-dyndns.py", line 32, in main
container     |     exposed_host_ipv6: str = ipaddress.IPv6Address(fritzbox.ipv6_prefix[:-1] + config.ipv6_node_id).exploded
container     |   File "/usr/local/lib/python3.10/ipaddress.py", line 1919, in __init__
container     |     self._ip = self._ip_int_from_string(addr_str)
container     |   File "/usr/local/lib/python3.10/ipaddress.py", line 1688, in _ip_int_from_string
container     |     raise AddressValueError(msg % (cls._HEXTET_COUNT, ip_str))
container     | ipaddress.AddressValueError: Exactly 8 parts expected without '::' in 'XXXX:XXXX:XXXX:YYYY:YYYY:YYYY:YYYY'
```

**Comment by f466162** [comment]
Still not solved, need to reopen.
